# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1svDI2pHuOmR-KNwByV36zzKMUjiAA3mg
"""

from google.colab import files

uploaded = files.upload()

import os
os.listdir()

!pip install -r requirements.txt
!pip install pydantic

!python main.py

!python llm_prompt_schema.py

import json
from typing import Dict, List, Literal
from pydantic import BaseModel, Field, model_validator

corpus_path = "outputs/corpus.jsonl"

records = []
with open(corpus_path, "r", encoding="utf-8") as f:
    for line in f:
        records.append(json.loads(line))

print("Number of market-window records:", len(records))

sample_record = records[len(records) // 2]
retrieved_context = sample_record["text"]

print("Sample date:", sample_record["date"])
print(retrieved_context[:800])

REGIME_CLASSIFIER_PROMPT = f"""
Based on the following market-window data, determine the current market regime.

Only use the information provided in the context below.

Possible regimes:
- bull
- bear
- high_volatility
- risk_off

When making the decision, look at:
- equity performance (returns, drawdown, moving average)
- volatility (VIX level and recent change)
- macro indicators (yield curve, Fed funds rate, CPI, unemployment, recession indicator)
- cross-asset signals (credit spread, equity-bond correlation)

If the signals are not fully consistent, reflect that in the confidence level.

Return the result in JSON format.

Context:
{retrieved_context}
"""

PORTFOLIO_ENGINE_PROMPT = """
Given a market regime classification and its supporting evidence, suggest a simple
portfolio allocation using SPY, IEF, and CASH.

Requirements:
- The weights must sum to 1
- In a bull market, allocate more to SPY
- In bear, high_volatility, or risk_off regimes, reduce SPY and increase IEF or CASH
- The result should be in JSON format
"""

class RegimeOutput(BaseModel):
    regime: Literal["bull", "bear", "high_volatility", "risk_off"]
    confidence: float = Field(ge=0, le=1)

    equity_reasoning: str
    volatility_reasoning: str
    macro_reasoning: str
    cross_asset_reasoning: str

    key_indicators: Dict[str, float]
    risk_flags: List[str]


class PortfolioOutput(BaseModel):
    SPY: float = Field(ge=0, le=1)
    IEF: float = Field(ge=0, le=1)
    CASH: float = Field(ge=0, le=1)

    action: Literal["increase_risk", "reduce_risk", "neutral"]
    rationale: str

    @model_validator(mode="after")
    def check_sum_to_one(self):
        total = self.SPY + self.IEF + self.CASH
        if abs(total - 1.0) > 1e-6:
            raise ValueError("SPY + IEF + CASH must sum to 1.")
        return self

regime_output = RegimeOutput(
    regime="bull",
    confidence=0.88,
    equity_reasoning=(
        "SPY has strong positive returns, a positive Sharpe ratio, "
        "no drawdown from the trailing 1-year high, and is above its "
        "200-day moving average."
    ),
    volatility_reasoning=(
        "VIX is low at 14.37 and realized volatility is moderate, "
        "so there is no clear high-volatility signal."
    ),
    macro_reasoning=(
        "The yield curve is positive, unemployment is 5.60%, and the "
        "NBER recession indicator is off."
    ),
    cross_asset_reasoning=(
        "Equity-bond correlation is negative and the credit proxy change "
        "is slightly negative, but these signals are not strong enough to "
        "override the positive equity and low-volatility evidence."
    ),
    key_indicators={
        "spy_ret_63d": 0.242,
        "spy_vol_63d": 0.141,
        "spy_maxdd_63d": -0.059,
        "spy_dd_from_1y_high": 0.0,
        "vix_last": 14.37,
        "unrate": 5.60
    },
    risk_flags=["minor_credit_proxy_weakness"]
)


portfolio_output = PortfolioOutput(
    SPY=0.70,
    IEF=0.25,
    CASH=0.05,
    action="increase_risk",
    rationale=(
        "Because the market is classified as bull, the portfolio keeps "
        "higher equity exposure while still holding some bonds and cash "
        "for diversification."
    )
)

print("\n=== Regime Classifier Prompt ===")
print(REGIME_CLASSIFIER_PROMPT[:2500])

print("\n=== Regime Output Schema Example ===")
print(regime_output.model_dump_json(indent=2))

print("\n=== Portfolio Engine Prompt ===")
print(PORTFOLIO_ENGINE_PROMPT)

print("\n=== Portfolio Output Schema Example ===")
print(portfolio_output.model_dump_json(indent=2))